name: Lint

on:
  pull_request:
  push:
     branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install
        run: npm ci
      - name: Run ESLint
        run: npm run lint -- --max-warnings=0
      - name: Check formatting
        run: npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,md}"
